// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// awa=it Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVoXmtJC7t9f3x5cKZjKewy5M8HjRkWpo',
    appId: '1:205862846678:web:fc463c1918968fb2a64977',
    messagingSenderId: '205862846678',
    projectId: 'sidakdesa-3d7cb',
    authDomain: 'sidakdesa-3d7cb.firebaseapp.com',
    storageBucket: 'sidakdesa-3d7cb.firebasestorage.app',
    measurementId: 'G-6CSEJ7HM3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPzlH35DQ58fnheGpq6vrMiEegGC0mK0',
    appId: '1:205862846678:android:8d2187f594b9baeaa64977',
    messagingSenderId: '205862846678',
    projectId: 'sidakdesa-3d7cb',
    storageBucket: 'sidakdesa-3d7cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbjWmx4rJYRYp8y44Z9w_tPUeT4zaYGM0',
    appId: '1:205862846678:ios:87811e5b9122153ca64977',
    messagingSenderId: '205862846678',
    projectId: 'sidakdesa-3d7cb',
    storageBucket: 'sidakdesa-3d7cb.firebasestorage.app',
    iosBundleId: 'com.example.projectSkripsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbjWmx4rJYRYp8y44Z9w_tPUeT4zaYGM0',
    appId: '1:205862846678:ios:87811e5b9122153ca64977',
    messagingSenderId: '205862846678',
    projectId: 'sidakdesa-3d7cb',
    storageBucket: 'sidakdesa-3d7cb.firebasestorage.app',
    iosBundleId: 'com.example.projectSkripsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVoXmtJC7t9f3x5cKZjKewy5M8HjRkWpo',
    appId: '1:205862846678:web:265c55549b2d8c22a64977',
    messagingSenderId: '205862846678',
    projectId: 'sidakdesa-3d7cb',
    authDomain: 'sidakdesa-3d7cb.firebaseapp.com',
    storageBucket: 'sidakdesa-3d7cb.firebasestorage.app',
    measurementId: 'G-T0512KGY4H',
  );
}
